Repository woowa-techcamp-2022/web-fleamarket-03, pull requests merged in 2022-08, with the labels that each got.

#2 프로젝트 시작 설정
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.tsx
  client/src/index.tsx
  client/tsconfig.json
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.controller.ts
  server/src/app.module.ts
  server/src/app.service.ts
  server/src/main.ts
  server/tsconfig.build.json
  server/tsconfig.json
Labels: pair, fe, be

#4 회원가입, 로그인에 필요한 백엔드 준비
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/enums/oAuthOrigin.enum.ts
  server/src/region/dto/createRegion.dto.ts
  server/src/region/dto/createUserRegion.dto.ts
  server/src/region/entities/region.entity.ts
  server/src/region/entities/userRegion.entity.ts
  server/src/region/region.controller.ts
  server/src/region/region.module.ts
  server/src/region/region.service.ts
  server/src/region/repository/region.repository.ts
  server/src/region/repository/userRegion.repository.ts
  server/src/user/dto/createUser.dto.ts
  server/src/user/dto/createUserRequset.dto.ts
  server/src/user/entities/user.entity.ts
  server/src/user/repository/user.repository.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: be, feature

#7 Login page 구현
  client/.env
  client/.eslintrc.js
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/public/goldmarket-logo.png
  client/src/App.tsx
  client/src/components/common/BasicButton.tsx
  client/src/constants/colors.ts
  client/src/constants/env.ts
  client/src/index.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/Routes.tsx
  client/src/style/GlobalStyle.ts
  client/src/utils/oAuth.tsx
  client/tsconfig.json
Labels: fe, feature

#8 Oauth 로그인 기본틀 구현
  client/.env
  client/.eslintrc.js
  client/.gitignore
  client/craco.config.js
  client/src/App.tsx
  client/src/components/RegionModal.tsx/index.tsx
  client/src/components/common/LoadingIndicator.tsx
  client/src/constants/env.ts
  client/src/constants/policy.ts
  client/src/customTypes/auth.ts
  client/src/customTypes/region.ts
  client/src/customTypes/user.ts
  client/src/hooks/useLogin.tsx
  client/src/hooks/useRegionModal.tsx
  client/src/index.tsx
  client/src/pages/ErrorPage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/OAuthRedirectPage.tsx
  client/src/pages/Routes.tsx
  client/src/pages/SignUpPage.tsx
  client/src/utils/oAuth.ts
  client/src/utils/oAuth.tsx
  client/src/utils/portal.ts
  client/src/utils/queryParser.ts
  client/tsconfig.json
  client/tsconfig.path.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/authentication/authentication.controller.ts
  server/src/authentication/authentication.module.ts
  server/src/authentication/authentication.service.ts
  server/src/authentication/types/index.ts
  server/src/main.ts
  server/src/user/dto/userResponse.dto.ts
  server/src/user/repository/user.repository.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: pair, fe, be, feature

#11 Refactor/10 oauth (strategy 패턴 적용)
  server/src/authentication/authentication.controller.ts
  server/src/authentication/authentication.module.ts
  server/src/authentication/authentication.service.ts
  server/src/authentication/service/authentication.service.ts
  server/src/authentication/service/token.service.ts
  server/src/authentication/strategy/baseOauth.strategy.ts
  server/src/authentication/strategy/github.strategy.ts
  server/src/authentication/strategy/oauthStrategy.factory.ts
Labels: be, feature

#16 Feat/9 basestyle (베이스 스타일 작성)
  client/src/App.tsx
  client/src/assets/icons/ChevronLeft.tsx
  client/src/assets/icons/calculator-fill.svg
  client/src/assets/icons/calculator-line.svg
  client/src/assets/icons/chat-fill.svg
  client/src/assets/icons/chat-line.svg
  client/src/assets/icons/github.svg
  client/src/assets/icons/google.svg
  client/src/assets/icons/heart-fill.svg
  client/src/assets/icons/heart-line.svg
  client/src/assets/icons/home-fill.svg
  client/src/assets/icons/home-line.svg
  client/src/assets/icons/kakao.svg
  client/src/assets/icons/user-fill.svg
  client/src/assets/icons/user-line.svg
  client/src/components/common/BasicButton.tsx
  client/src/components/common/Button.tsx
  client/src/components/common/NavigationBar.tsx
  client/src/components/common/Text.tsx
  client/src/constants/colors.ts
  client/src/constants/fonts.ts
  client/src/pages/LoginPage.tsx
  client/src/style/mixin.ts
  client/tsconfig.path.json
Labels: pair, fe, feature

#22 Feat/15 regionmodal (동네선택 모달 구현)
  client/.eslintrc.js
  client/src/App.tsx
  client/src/apis/region.ts
  client/src/components/RegionModal.tsx/RegionSearchList.tsx
  client/src/components/RegionModal.tsx/index.tsx
  client/src/components/common/Text.tsx
  client/src/customTypes/region.ts
  client/src/hooks/useRegionModal.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/utils/common.ts
  client/tsconfig.path.json
Labels: fe, feature

#26 Feat/25 productentity (Product 엔티티 구현 및 Get api 구현)
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/enums.ts
  server/src/common/enums/oAuthOrigin.enum.ts
  server/src/product/dto/getRegionProducts.dto.ts
  server/src/product/entities/category.entity.ts
  server/src/product/entities/like.entity.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.controller.ts
  server/src/product/product.module.ts
  server/src/product/product.service.ts
  server/src/product/repository/product.repository.ts
  server/src/region/entities/region.entity.ts
  server/src/region/entities/userRegion.entity.ts
  server/src/user/entities/user.entity.ts
Labels: be, feature

#27 Feat/19 mainpagemarkup (메인페이지 마크업)
  client/src/apis/product.ts
  client/src/assets/icons/AddIcon.tsx
  client/src/assets/icons/CategoryIcon.tsx
  client/src/assets/icons/ChatIcon.tsx
  client/src/assets/icons/HeartIcon.tsx
  client/src/assets/icons/MapPinIcon.tsx
  client/src/assets/icons/MenuIcon.tsx
  client/src/assets/icons/UserIcon.tsx
  client/src/assets/icons/chat-fill.svg
  client/src/assets/icons/chat-line.svg
  client/src/assets/icons/heart-fill.svg
  client/src/assets/icons/heart-line.svg
  client/src/assets/icons/user-fill.svg
  client/src/assets/icons/user-line.svg
  client/src/components/MainPageNavigationBar/MainNavTitle.tsx
  client/src/components/MainPageNavigationBar/index.tsx
  client/src/components/ProductItem/index.tsx
  client/src/components/RegionModal.tsx/RegionSearchList.tsx
  client/src/components/common/CircleButton.tsx
  client/src/components/common/CountIndicator.tsx
  client/src/components/common/LikeButton.tsx
  client/src/components/common/Text.tsx
  client/src/components/common/Thumbnail.tsx
  client/src/constants/padding.ts
  client/src/customTypes/product.ts
  client/src/pages/MainPage.tsx
  client/src/pages/Routes.tsx
  client/src/pages/SignUpPage.tsx
  client/src/utils/common.ts
  client/src/utils/product.ts
  server/src/product/product.controller.ts
Labels: fe, feature

#32 Feat/30 reactquery (로그인 및 회원가입 로직에 리액트 쿼리 적용)
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/apis/user.ts
  client/src/hooks/useLogin.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/OAuthRedirectPage.tsx
  client/src/pages/SignUpPage.tsx
  server/src/authentication/authentication.controller.ts
  server/src/authentication/decorators/use.auth.guard.decorator.ts
  server/src/authentication/guards/auth.guard.ts
  server/src/authentication/service/authentication.service.ts
  server/src/authentication/service/token.service.ts
  server/src/product/product.controller.ts
  server/src/product/product.module.ts
  server/src/user/entities/user.entity.ts
  server/src/user/repository/user.repository.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: enhancement, fe, be

#38 Feat/34 loginstate (react query 적용 및 axios interceptor를 이용하여 로그인 유지)
  client/public/index.html
  client/src/App.tsx
  client/src/apis/myAxios.ts
  client/src/apis/product.ts
  client/src/apis/region.ts
  client/src/apis/user.ts
  client/src/components/MainPageNavigationBar/MainNavTitle.tsx
  client/src/customTypes/user.ts
  client/src/hooks/useLogin.tsx
  client/src/index.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/Routes.tsx
  server/package-lock.json
  server/package.json
  server/src/authentication/authentication.controller.ts
  server/src/authentication/guards/auth.guard.ts
  server/src/authentication/service/authentication.service.ts
  server/src/authentication/service/token.service.ts
  server/src/authentication/strategy/baseOauth.strategy.ts
  server/src/main.ts
  server/src/region/entities/userRegion.entity.ts
  server/src/region/region.service.ts
  server/src/user/repository/user.repository.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: fe, be, feature

#39 Feat/29 productdetailapi (상품 디테일 페이지에 필요한 API 구현)
  server/src/product/dto/like.dto.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.controller.ts
  server/src/product/product.module.ts
  server/src/product/product.service.ts
  server/src/product/repository/like.repository.ts
  server/src/product/repository/product.repository.ts
Labels: be, feature

#42 Feat/28 detailpage (상품 디테일 페이지 마크업 및 드롭다운 틀 구현)
  client/src/App.tsx
  client/src/apis/product.ts
  client/src/assets/icons/ChevronDown.tsx
  client/src/assets/icons/ChevronLeft.tsx
  client/src/assets/icons/MoreIcon.tsx
  client/src/components/ChatButton/index.tsx
  client/src/components/DetailPageNavigationBar/index.tsx
  client/src/components/ImageSlider.tsx/index.tsx
  client/src/components/MoreButton/index.tsx
  client/src/components/ProductItem/index.tsx
  client/src/components/SaleStateSelector/index.tsx
  client/src/components/common/Caption.tsx
  client/src/components/common/DropDown.tsx
  client/src/components/common/NavigationBar.tsx
  client/src/components/common/Text.tsx
  client/src/customTypes/product.ts
  client/src/customTypes/user.ts
  client/src/pages/DetailPage.tsx
  client/src/pages/Routes.tsx
  client/src/utils/common.ts
  client/src/utils/product.ts
  server/src/app.module.ts
  server/src/product/dto/getProductDetail.dto.ts
  server/src/product/entities/product.entity.ts
  server/src/product/product.controller.ts
  server/src/product/product.service.ts
  server/src/product/repository/product.repository.ts
Labels: fe, feature

#80 Feat/ux (UX 향상)
  client/public/Icons/appliance.png
  client/public/Icons/baby.png
  client/public/Icons/beauty.png
  client/public/Icons/book.png
  client/public/Icons/digital.png
  client/public/Icons/female-fashion.png
  client/public/Icons/furniture.png
  client/public/Icons/game.png
  client/public/Icons/gold.png
  client/public/Icons/life.png
  client/public/Icons/male-fashion.png
  client/public/Icons/pet.png
  client/public/Icons/plant.png
  client/public/Icons/sports.png
  client/public/images/empty.png
  client/public/images/goldmarket-logo.png
  client/public/images/sadBaedal.png
  client/src/App.tsx
  client/src/apis/user.ts
  client/src/components/CategoryPage/CategoryGrid.tsx
  client/src/components/CategoryPage/CategoryItem.tsx
  client/src/components/ChattingRoom/ChatInput.tsx
  client/src/components/InfoButton/index.tsx
  client/src/components/MainPageNavigationBar/MainNavTitle.tsx
  client/src/components/MyTab/ChattingList.tsx
  client/src/components/MyTab/ChattingRoom.tsx
  client/src/components/MyTab/LikedProductList.tsx
  client/src/components/MyTab/MySalesProductList.tsx
  client/src/components/ProductItemList/ProductItem/index.tsx
  client/src/components/ProductItemList/index.tsx
  client/src/components/common/CountIndicator.tsx
  client/src/components/common/EmptyIndicator.tsx
  client/src/components/common/LoadingIndicator.tsx
  client/src/hooks/chat/useChat.tsx
  client/src/hooks/useLogin.tsx
  client/src/pages/DetailPage.tsx
  client/src/pages/LogOutPage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/ProductRegistPage.tsx
  client/src/queries/useChatRoom.ts
  client/src/style/GlobalStyle.ts
  server/src/authentication/authentication.controller.ts
  server/src/authentication/service/authentication.service.ts
  server/src/common/enums.ts
  server/src/region/entities/userRegion.entity.ts
  server/src/user/repository/user.repository.ts
Labels: fe
